### PR TITLE
update GordayFilter: support non-parallel lights

### PR DESCRIPTION
**Pull request by finscn**
More details at : https://github.com/pixijs/pixi-filters/issues/65

### CODE REVIEW

**Comment by finscn** [comment]
I can't understand you clearly.  Welcome(& please) to refactor it , thanks

**Comment by finscn** [comment]
BTW: I think we should allow some `breaking changes` in this project. because it's a newborn ,  And some filters  are  few(less ? forgive my english)  people used .

**Comment by finscn** [comment]
@bigtimebuddy  , the logic I think is good. 

But `focal` is not a good name , I think.
 the `focal` is about `camera shooting` , not about `lighting`.
in lighting system , it's called  `point light source` .

**Comment by bigtimebuddy** [comment]
Note sure I agree about the name. Focal: relating to the center or main point of interest. I think that applies here, not just for cameras.

**Comment by finscn** [comment]
OK. everybody's english is better than me.

**Comment by bigtimebuddy** [comment]
focalPoint sounds better, I’ll change

**Comment by finscn** [comment]
I like `center`

**Pull request merged**
