### PR TITLE
Add KawaseBlurFilter

### PR DESCRIPTION
**Pull request by finscn**
It's a more faster blur algorithm than Gaussian Blur.

more details at :  https://software.intel.com/en-us/blogs/2014/07/15/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms

P.S. : @bigtimebuddy  , I don't add any document about it , because it's too hard to me in this filter...
And I think this filter is not for `junior user` ,  if an user  wants to use it well , he/she needs to understand the algorithm.

After this PR be merged , I will update AdvancedBloomFilter , make it support KawaseBlurFilter

### CODE REVIEW

**Comment by finscn** [comment]
About performance , you could see this :  http://finscn.github.com/pixi-filters/index.html

try `<fish> Blur filter (pixi.js)` & `<fish> KawaseBlur filter` , you will see KawaseBlur is faster.
And in some cases , it's more than 4x faster , and in some cases it's less than 2x.
But whatever , it's always faster.

**Comment by bigtimebuddy** [comment]
@finscn I like this filter and the performance benefits but it's very difficult to use. Can you suggest anyways we might improve to make it more usable?

**Comment by finscn** [comment]
I have an idea. 
give me sometimes.

**Comment by finscn** [comment]
@bigtimebuddy  , Done.
Please review & refactor it , make it better , thanks.

Now, it could generate `kernels` by `blur & quality`.

And for Advanced Users , they still could custom `kernels` by themselves.

**Pull request merged**
