### PR TITLE
Add ColorMapFilter

### PR DESCRIPTION
**Pull request by finscn**
More details at :  https://github.com/pixijs/pixi-filters/issues/61

inspired by : 
https://www.youtube.com/watch?v=rfQ8rKGTVlg#t=25m03s
https://github.com/hughsk/webgl-texture3d
https://www.defold.com/tutorials/grading/

### CODE REVIEW

**Comment by finscn** [comment]
online demo :　http://fatidol.com/pixi-filters/

**Comment by bigtimebuddy** [comment]
Can we rename this to ColorMapFilter?

**Comment by finscn** [comment]
or ColorMappingFilter ?  How do you think about it , @ivanpopelyshev ?

**Comment by finscn** [comment]
mapping is also a nouns.  

mapping [ 'mæpiŋ ]
n.
a function such that for every element of one set there is a unique element of another set

example: ORM : Object Relational Mapping ( in ORM , mapping is a nouns)

**Comment by bigtimebuddy** [comment]
I stand corrected! I read it more as an action.

I'm fine with either, but not ColorAdjustFilter.

**Comment by finscn** [comment]
ColorMapFilter or ColorMappingFilter ? 

And if call this filter `ColorMapFilter/ColorMappingFilter` ,  shall we change the `AdjustmentFilter` to `ColorAdjustFilter/ColorAdjustmentFilter` ?

**Comment by finscn** [comment]
OK. I'll use `ColorMapFilter` , because there is a filter named `SimpleLightMapFilter`.
`both map` is better than `one map, one mapping`.

**Comment by bigtimebuddy** [comment]
Thanks @finscn, good work.

**Pull request merged**
