### PR TITLE
Improved Godrays performance

### PR DESCRIPTION
**Pull request by alaingalvan**
Tristan Le Moigne (https://twitter.com/tristanlemoigne) DM'd me on Twitter asking for ways to improve the performance of this shader, so I've gone ahead and done just that. A demo for these changes can be found in https://codepen.io/alaingalvan/pen/ICasz.

I tried to make this change as hot-swapable as possible, reusing as much of the original code here.

1. Using 3D Gradient noise by Inigo Quilez instead of Simplex Noise by Ashima Arts and Stefan Gustavson
2. Using 4 turbulence layers instead of 6.
3. Since noise functions are much smaller, opting to put everything in `godray.frag`
4. There was a typo in the name `gorday.frag`, most likely it was intended to be `godray.frag`, renamed the file to that.

### CODE REVIEW

**Comment by themoonrat** [comment]
So had a little go of putting this into our game, to see if it improved performance. On that point, it definitely does! Which is awesome, as the artists love this effect.

With the same settings, here are the before:
godray - before

and after:
godray - after

Couple of things I've noticed
1: The rays look a bit more 'stringy' in your version, which isn't quite so pleasing on the eye
2: We tween the 'time' property; this makes the rays move super fast compared to the current implementation!

The config used is
```
 {
	"gain": 0.43,
	"lacunrity": 1.3,
	"parallel": true,
	"time": 0,
	"angle": 44
}
```

**Comment by alaingalvan** [comment]
Thanks for reviewing this @themoonrat! I'll go ahead and modify the shader this weekend such that it behaves as close to the original settings as possible. 👍

**Comment by themoonrat** [comment]
Looking forward to it :) We had to remove a full screen godray filter from a game because of performance issues; would love to be able to re-instate it.

**Comment by bigtimebuddy** [comment]
@alaingalvan did you ever get time to work on @themoonrat's feedback? Would love to get this in, but agree that it would be a visual departure. Can we get this any closer visually?

**Comment by alaingalvan** [comment]
Hi, I this project slipped my mind till you let me know @bigtimebuddy, thanks!

I went ahead and tuned the shader to match the original godray behavior as closely as possible, here's a comparison between the original and the new version:

https://codepen.io/alaingalvan/full/poJobQO

vs.

https://codepen.io/alaingalvan/full/ICasz

I'll keep tuning it and patch this branch when it's as close to the other as I can make it. 👍

**Comment by bigtimebuddy** [comment]
Looking better and thanks for getting back so quickly.

One small piece of feedback is the original version has much more contrast (brighter streaks) then your newest version where all the rays are very similar/flat.

**Comment by finscn** [comment]
@alaingalvan  could you update this pr for new version of pixi-filters , please?

**Comment by bigtimebuddy** [comment]
@alaingalvan I'd really like to see this get in, but seem like it still needs some work to not make it visually breaking. You still available to polish it? If not, I think we should create a GodRay2 filter so that it doesn't break users who are using the current ray and allow users to opt-in to the more performance.

**Comment by bigtimebuddy** [comment]
I'm going to close this PR as it has gotten stale. If someone want to pick-up this work, please make a new PR. Thanks.

**Pull request closed without merging**
