### PR TITLE
Made properties in DropShadowFilterOptions optional to match docs

### PR DESCRIPTION
**Pull request by zfmarkham**
Mentioned in issue #177

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thank you!

**Comment by bigtimebuddy** [comment]
Could you also update the DropShadowFilter here: https://github.com/pixijs/pixi-filters/blob/master/bundle/types.d.ts

**Comment by zfmarkham** [comment]
Just made that change to https://github.com/pixijs/pixi-filters/blob/master/bundle/types.d.ts too

**Comment by bigtimebuddy** [comment]
Thanks @zfmarkham!

**Pull request merged**
