### PR TITLE
Improve OutlineFilter

### PR DESCRIPTION
**Pull request by finscn**
* add a new argument: `quality`
* use ANGLE_STEP(quality, sample) instead of THICKNESS ( they are different things)
* fix bug about #107 
* optimal performance (just  a little) 
* update outline's demo

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
This looks good @finscn. Thank you for pulling this together.

The only thing I don't like are the changes to **tools/demo/src/filters/outline.js**. I think for demo purposes, setting the quality at something the looks reasonably good is sufficient. I don't think this is valuable that people should be able to change `quality`. Although, I think your solution is clever, just a little unnecessary.

**Comment by finscn** [comment]
I know in real use case , users shouldn't change quality ( need to create different filter instances for different quality);
But in demo ,  if user set  thickness = 20 , the quality must be 1.0  (sampler = 100) . 
If I set quality = 1 , the performance will be bad.

**Comment by finscn** [comment]
OK ， I see。 But there is a question.
In other filters ,  all of them use  `%uppercase-letter-var%` for replacing in shader.
in this filter use  `${angleStep}` is so strange.

I think they should be uniform style.

**Comment by bigtimebuddy** [comment]
Godray uses ${perlin}

**Comment by finscn** [comment]
@ivanpopelyshev  , in fact , I also like `magic string style` . So maybe we could refactor all filter's `uppercase replacement string` to `magic string style` .

**Comment by bigtimebuddy** [comment]
I agree @finscn, maybe a new PR for that?

**Pull request merged**
