### PR TITLE
Adds new GodrayFilter

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
I cant find whats wrong with building process.

@bigtimebuddy adding new filter is not easy.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Please help me with new error

**Comment by bigtimebuddy** [comment]
I fixed a bunch of issues including adding to docs, fixing the example, adding a time slider, etc.

There are two issues with this filter right now:

1. There's no way to adjust the contrast/intensity of the multiply of the filter. In the case of this fish scene, it is a very subtle effect. Would be nice to add an opacity/intensity property.
2. It creates a black background with the whole filterArea (see below). There should be a transparent/white frame around the image.

godray

**Comment by bigtimebuddy** [comment]
Also, I will create a Wiki page on adding new filters. There are a lot of pieces to hook up.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev I also created some documentation for adding new filters: https://github.com/pixijs/pixi-filters/wiki/Adding-Filters

**Comment by bigtimebuddy** [comment]
I added a few features to this, mainly adding the following customizable properties:

* gain
* lacunarity
* angle

**Comment by finscn** [comment]
I think we could do this in js : 
```
    float xx = cos(radians(angle));
    float yy = sin(radians(angle));
```

if it's in frag shader , every pixel will compute it .

**Comment by finscn** [comment]
@bigtimebuddy   do this maybe could fix the bug about angle : 
```
dir.y *= dimensions.y / dimensions.x ;
```
or 
```
dir.y *= filterArea.y / filterArea.x ;
```

**Comment by ivanpopelyshev** [comment]
Actually, good idea. lets submit dir instead :) working on it...

**Comment by ivanpopelyshev** [comment]
I'm trying to fix it, but have problems with build (again!) and .. where is the place where we change "time" variable?

**Comment by bigtimebuddy** [comment]
"npm run examples"?

**Comment by ivanpopelyshev** [comment]
OK, i cant figure our formulas yet :( Tried multiple things but so far it didnt work

**Comment by bigtimebuddy** [comment]
godray

This looks great, thanks @ivanpopelyshev for the math fix.

**Pull request merged**
