### PR TITLE
Refactor Demo

### PR DESCRIPTION
**Pull request by bigtimebuddy**
Replaces #81 

This uses Rollup to build the demo project in **tools/demo**.

### CODE REVIEW

**Comment by finscn** [comment]
I can't wait it.

**Comment by finscn** [comment]
Please resize bg sprite when window resize.
If do that users will can't know `If "the bg resize effect" is filter's effect`

**Comment by bigtimebuddy** [comment]
I’m not sure I agree with your concern about the background sprite. What about a proportional scale? So it maintains the same aspect ratio?

**Comment by finscn** [comment]
The proportional scale is better than current setting. 
But if only scale bg  and don't scale  the  fishes , it'll puzzle somebody still, e.g. Me.

**Pull request merged**
