### PR TITLE
Improve and fix glow filter

### PR DESCRIPTION
**Pull request by laino**
The old glow filter had a number of issues which this PR addresses. 

- It unnecessarily calculated ``maxTotalAlpha`` by adding stuff up in a loop, even though that value can be statically calculated with ``distance * (distance + 1.0) * outerLoopIterations``. See [this wikipedia article](https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF) if you're interested in the details.

- The final calculation used a few tricks to avoid dividing by zero. The new code doesn't even have to worry about that anymore and is much simpler too.

- The old filter did extra loops where ``(distance - curDistance)`` was ``0`` and multiplied with the result. Essentially the old filter did a lot of work for the final distance step, then discarded the result.

- A few things could be calculated once in the outer loop instead of the inner one or expressed using vector math.

- Distance can't be changed because it's used in a loop and thus needs to be put into the fragment source. The old code gave it as an uniform as well and let the user change it. It's now read only. Changing distance mostly just lead to fun artifacts if your filter had any ``innerStrength``.

If we decoupled distance steps from distance step size we could make that freely configurable at the cost of slightly more computation. Maybe I'll think about that tomorrow.

- Using not maxed out color values like ``0xf24545`` lead to some fun artifacts (increase inner and out strength to really see them):

</img>

- The filter should look pretty much identical to the old one except where the old one ran into problems.

- Overall it's a lot less and more readable code, though I added blank lines and eliminated really long lines for readability.

### CODE REVIEW

**Comment by laino** [comment]
I fixed some artifacts around edges of sprites when using really dark color values. Also added support for fractional distance values (the calculation just didn't take it into account and ended up being 'incorrect' ever so slightly - not sure if it was even visible).

**Comment by laino** [comment]
.... And in the process I added (some) the color discoloration bugs of the old filter back in... Hmmm.

**Comment by laino** [comment]
My math was off. To make fractional distance values work correctly one has to unroll the last step of the loop with the "fractional" step.

Not sure if this is even worth it because it makes the code more complicated.

Maybe distance should just be rounded.

**Comment by bigtimebuddy** [comment]
Screen Shot 2020-02-04 at 3 20 08 PM

@laino love this fix. performance is much better. One question: Is there anyway to smooth or avoid the weird spike artifacts on sharp corners?

**Comment by laino** [comment]
The spikes are related to the "quality steps", basically the pattern we use to test in various distances from the current pixel. They could probably be reduced by (fake) randomizing/dithering the angles to some degree or just by increasing the quality value.

**Comment by bigtimebuddy** [comment]
Thank you @laino!

**Pull request merged**
