### PR TITLE
Add filterClamp to KawaseBlur calculation

### PR DESCRIPTION
**Pull request by nikkop**
The KawaseBlur filter is not blurring the right and bottom side/edges
correctly as the blur will "bleed" and create black edges. By using filterClamp in the
calculation the bleed will not occur.

This can easily be seen by going to the [demo](http://pixijs.io/pixi-filters/tools/demo/), enable KawaseBlurFilter and looking at the right side and bottom side.

The error:
kawaseblurerror

After fix:
kawaseblurfix

filterClamp solution from  [@ivanpopelyshev](https://github.com/pixijs/pixi.js/issues/2816#issuecomment-240162667)

### CODE REVIEW

**Comment by finscn** [comment]
I think the `filterClamp` should be an option.

`always do filterClamp` may not apply to all use case.

**Comment by ivanpopelyshev** [comment]
Padding isnt helping. And clamping is nothing compared to 4 samplers.

**Comment by finscn** [comment]
@ivanpopelyshev  , I mean that   Padding could make 4 sides with transparent-blur-edge , not only right & down.

**Comment by ivanpopelyshev** [comment]
That's right, but if your filterArea is less than filtered element, it might be a problem.

**Comment by nikkop** [comment]
@finscn When is this side-effect wished for when using a blur? I don't understand why it might be an issue.

**Comment by bigtimebuddy** [comment]
Here are two examples using this PR and the current KawaseBlurFilter with a `filterArea` being set. As you can see there's a significant visual difference between the two. 

I mostly agree with @finscn here. I think KawaseBlurFilter should work like BlurFilter. Without the ability to opt-in/out of clamping, this change makes it not an analogous replacement for BlurFilter. Seems more flexible without clamping. What do you guys think?

screen shot 2018-02-24 at 3 57 34 pm
screen shot 2018-02-24 at 3 55 32 pm
screen shot 2018-02-24 at 3 55 52 pm

**Comment by nikkop** [comment]
@bigtimebuddy I can now see what you mean and I understand your point. Nice illustrations of the filters. 
How about giving the possibility to use it, with the default being off? This way replacement for BlurFilter will work and at the same time allow clamping of it.

**Comment by bigtimebuddy** [comment]
Good idea, I like that.

**Comment by bigtimebuddy** [comment]
I would like to add this to v2.6.0. If you can work on it soon let me know, otherwise, I'll make the release and we'll address in the next release.

**Comment by nikkop** [comment]
@bigtimebuddy I can fix it tonight (in approx 16 hours~). Is that fine by you?

**Comment by finscn** [comment]
@nikkop , I have a suggestion.
Don't add  ` if ... else ...` to shader, it will breakdown performance.

change the source string of shader in JS, please.

**Comment by bigtimebuddy** [comment]
Works for me @nikkop. Thanks for your help! I think @finscn's suggestion is a good one, and to try to avoid if/else statements in the shaders.

**Comment by nikkop** [comment]
@finscn @bigtimebuddy Do you guys mean having two shaders (one with clamp and one without) and depending on the value passed for clamping (true/false) choose the appropriate shader?

**Comment by bigtimebuddy** [comment]
I think @finscn was suggesting doing something like https://github.com/pixijs/pixi-filters/blob/master/filters/godray/src/GodrayFilter.js#L30 where you replace the string. But it might be cleaner to have to separate frag files, one for clamped and one unclamped and have an option to choose.

**Comment by bigtimebuddy** [comment]
@nikkop any movement on this? If not, no worries, I'm happy to make these changes if you're busy. Let me know. I'm eager to get v2.6.0 out the door.

**Comment by nikkop** [comment]
@bigtimebuddy Pardon me, I was busy last night and couldn't make it. It's absolutely fine by me if you would do it, I would even prefer it as I then can see how the implementation with the two shaders take place :) Do you mind?

**Comment by finscn** [comment]
Don't forget that the `BlurFilter` also needs this feature.

**Pull request merged**
