### PR TITLE
fix LUT doesn't bind correctly

### PR DESCRIPTION
**Pull request by djmisterjon**
related to :
https://github.com/pixijs/pixi-filters/issues/171

### CODE REVIEW

**Comment by Dairnon** [comment]
Thank you @djmisterjon 

Hopefully someone gets time to review now that the busy holidays are over.

**Comment by bigtimebuddy** [comment]
@djmisterjon: thoughts about @ivanpopelyshev's feedback?

**Comment by djmisterjon** [comment]
@bigtimebuddy hum, maybe see with @Dairnon  code, i can not experiment or debug because i dont have a web server environment to run this.
I will maybe try next week study and try to install a web servor for debug pixi-filter with 
https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare

For now i can not test or debug live gl code

**Comment by djmisterjon** [comment]
ok i think this one can be remove and use this new pr
https://github.com/pixijs/pixi-filters/pull/182

**Pull request closed without merging**
