### PR TITLE
Refactor example

### PR DESCRIPTION
**Pull request by finscn**
* extract main logic to main.js
* extract css
* use EventEmitter as event manager
* When resize window, won't resize bg sprite.
* per-filter with per js-file
* change the logic of `Pause` : pause animation & motion of sprites , but not pause game tick & game time. ( https://github.com/pixijs/pixi-filters/pull/79 )

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
I agree that this needs a refactor, but this is not really the approach I’d like to take with the examples. I would much rather make it a module that is built in tools folder with Rollup and removed from the top-level examples folder.

**Comment by bigtimebuddy** [comment]
Also I want to keep the pause resume functionality the same and not change. This was designed to stop tick updates to keep my computer from overheating and to do screenshots. My suggestion is add an onChange handler on each datgui property and manually render.

**Comment by finscn** [comment]
OK. After you refactor example , I'll create the PR about  `MotionBlur , RadialBlur and KawaseBlur`.
The current example make me crazy. 

BTW , `don't resize bg sprite` is very important.
When I resize window , if `bg` is also resized , I'll find some bugs  about `wrong aspect ratio` difficultly.

**Comment by bigtimebuddy** [comment]
Replaced with #85

**Pull request closed without merging**
